services:
  db:
    image: postgres:14-alpine
    container_name: salon_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # Docker Compose автоматически прочитает .env файл и подставит переменные
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # --- ДОБАВЬТЕ ЭТОТ БЛОК ---
    ports:
      - "5432:5432"
    # --- КОНЕЦ БЛОКА ---

    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: salon_api_service
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload 
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    # Указываем Docker'у использовать наш .env файл для этого сервиса
    env_file:
      - .env
    environment:
      - RUNNING_IN_DOCKER=1 # <--- ДОБАВЬТЕ ЭТУ СТРОКУ
    restart: unless-stopped
  
  bot:
    build: .
    container_name: salon_telegram_bot
    command: python3 bot.py
    volumes:
      - .:/app
    depends_on:
      - api
    # И для этого тоже
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres_data:
