services:
  db:
    image: postgres:14-alpine
    container_name: salon_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - salon_network

  redis:
    image: redis:7-alpine
    container_name: salon_redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - salon_network

  api:
    build: .
    container_name: salon_api_service
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
      - RUNNING_IN_DOCKER=true
    depends_on:
      - db
    networks:
      - salon_network

  bot:
    build: .
    container_name: salon_telegram_bot
    command: python bot.py
    volumes:
      - .:/app
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_URL=http://api:8000
      - YANDEX_API_KEY=${YANDEX_API_KEY}
      - YANDEX_FOLDER_ID=${YANDEX_FOLDER_ID}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - api
      - redis
    networks:
      - salon_network

volumes:
  postgres_data:
  redis_data:

networks:
  salon_network:
    driver: bridge